# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Khulnasoft < Formula
    desc "Khulnasoft CLI"
    homepage "https://khulnasoft.com"
    version "{{ .Version }}"
    license "MIT"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/khulnasoft/cli/releases/download/v{{ .Version }}/khulnasoft_darwin_arm64.tar.gz"
        sha256 "{{ .Checksum.khulnasoft_darwin_arm64 }}"
  
        def install
          bin.install "khulnasoft"
          (bash_completion/"khulnasoft").write `#{bin}/khulnasoft completion bash`
          (fish_completion/"khulnasoft.fish").write `#{bin}/khulnasoft completion fish`
          (zsh_completion/"_khulnasoft").write `#{bin}/khulnasoft completion zsh`
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/khulnasoft/cli/releases/download/v{{ .Version }}/khulnasoft_darwin_amd64.tar.gz"
        sha256 "{{ .Checksum.khulnasoft_darwin_amd64 }}"
  
        def install
          bin.install "khulnasoft"
          (bash_completion/"khulnasoft").write `#{bin}/khulnasoft completion bash`
          (fish_completion/"khulnasoft.fish").write `#{bin}/khulnasoft completion fish`
          (zsh_completion/"_khulnasoft").write `#{bin}/khulnasoft completion zsh`
        end
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/khulnasoft/cli/releases/download/v{{ .Version }}/khulnasoft_linux_arm64.tar.gz"
        sha256 "{{ .Checksum.khulnasoft_linux_arm64 }}"
  
        def install
          bin.install "khulnasoft"
          (bash_completion/"khulnasoft").write `#{bin}/khulnasoft completion bash`
          (fish_completion/"khulnasoft.fish").write `#{bin}/khulnasoft completion fish`
          (zsh_completion/"_khulnasoft").write `#{bin}/khulnasoft completion zsh`
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/khulnasoft/cli/releases/download/v{{ .Version }}/khulnasoft_linux_amd64.tar.gz"
        sha256 "{{ .Checksum.khulnasoft_linux_amd64 }}"
  
        def install
          bin.install "khulnasoft"
          (bash_completion/"khulnasoft").write `#{bin}/khulnasoft completion bash`
          (fish_completion/"khulnasoft.fish").write `#{bin}/khulnasoft completion fish`
          (zsh_completion/"_khulnasoft").write `#{bin}/khulnasoft completion zsh`
        end
      end
    end
  end