theme = "docdock"
baseurl = "https://khulnasoft.github.io/cli"
title = "Khulnasoft CLI Documentation"
publishDir = "../public"
languageCode = "en-us"
DefaultContentLanguage = "en"


pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = true # default is false
disableSearch = false # default is false
disableNavChevron = true # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter

[blackfriday]
  smartDashes = false

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/khulnasoft/cli"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-camera'></i> External Resources"
url = "/external-resources"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Khulnasoft Documentation"
identifier = "hugodoc"
url = "https://docs.khulnasoft.com"
weight = 20
